timeout: 0
/BitOS
    protocol: limine
    path: boot():/boot/bitos
    resolution: 1280x720x32
    cmdline: nx=on log=debug watchdog=off boot.mode=desktop
    module_path: boot():/boot/initramfs.cpio
    module_string: initramfs
